FROM golang:1.21

WORKDIR /app

COPY . .

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
RUN mv migrate.linux-amd64 /usr/local/bin/migrate
RUN migrate -path ./migrations -database postgres://postgres:example@192.168.80.2:5432/postgres?sslmode=disable up 

