services:
  govel-panel-db-test:
    container_name: govel-panel-db-test
    build:
      context: .
      dockerfile: Dockerfile.database
    restart: always
    networks:
      - govel-panel-network
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
  test:
    container_name: govel-test
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - govel-panel-db-test
    networks:
      - govel-panel-network
    command: go test -v ./tests/...
  govel-app:
    container_name: govel-app
    build: .
    ports:
      - "8080:8080"
    depends_on: 
     - govel-panel-db
    networks:
      - govel-panel-network
  govel-panel-db:
    container_name: govel-panel-db
    build:
      context: .
      dockerfile: Dockerfile.database
    restart: always
    networks:
      - govel-panel-network
    volumes:
      - greenlight-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
networks:
  govel-panel-network:
    driver: bridge
volumes:
  greenlight-volume: